### PR TITLE
Add functions for TMB & MSI plots

### PR DESCRIPTION
**Pull request by Aisha-D**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1)

### CODE REVIEW

**Review by jsunhs — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`bin/main.py` line 328 at r1](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1#-Np_xDw00ZYPFz_rgQry:-Np_xDw00ZYPFz_rgQrz:byrge8s) ([raw file](https://github.com/eastgenomics/TSO500_Compare_Output/blob/03196de526197c87efe7580d458dd747324dfafa/bin/main.py#L328)):*
> ```Python
>     barplots(dat, "Usable MSI Sites ")
>     barplots(dat, "Total MSI Sites Unstable ")
>     barplots(dat, "Percent Unstable MSI Sites ")
> ```

It will be more clear to mark "Percent" as % and set the ylim to be [0-100%] on y axis.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsunhs)

___
*[`bin/main.py` line 328 at r1](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1#-Np_xDw00ZYPFz_rgQry:-NpdBwgr4nafPXdm6vzR:bejiy4q) ([raw file](https://github.com/eastgenomics/TSO500_Compare_Output/blob/03196de526197c87efe7580d458dd747324dfafa/bin/main.py#L328)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

It will be more clear to mark "Percent" as % and set the ylim to be [0-100%] on y axis.
</blockquote></details>

Done, the plot looks like this now

**Review by jsunhs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by jsunhs — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by jsunhs — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/TSO500_Compare_Output/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
